### ISSUE TITLE
Setting up a hillshading server

### ISSUE THREAD

**Issue by janvonquaeldich** [Karry/hillshade-tile-server#1]
Hi Lukáš,
I'm happy to have found your project. I'm Jan from quaeldich.de, the leading online platform for mountain road cycling in the german area. I've seen on your personal web site that you are into biking too. If it's also road biking, you might have heard of us.

I've also seen your hillshading example and I would like to use these tiles on quaeldich now the wflabs hillshading is discontinued. 

The tile load is quite massive, as we hit more than a million page views per month. I don't think your infrastructure could cope with this load and I would not dare to try. Do you consider it possible to set up such a server for us on a project basis? What big a VM would we need?

If you can't do it, I would try to engage someone else :)

Thanks for answering, Jan

**Comment by Karry** [comment]
Hi Jan. 

You are right, I love road cycling, but I don't heard about quaeldich.de before unfortunately. My German is not the best :-) 

I'm happy that you like my simple hillshade server. As it is server for my non-profit hobby project, "infrastructure" is not ready for production usage. In reality, it is served by Raspberry Pi 3 - ARM board with with 1 GiB of ram memory. It is able to render hilllshade tiles in two threads, so when tiles are not ready in cache, it is pretty slow. 

System requirements: 
 - 80G disk space (read-only) for raw elevation data (whole world, see [viewfinderpanoramas.org](http://viewfinderpanoramas.org/Coverage%20map%20viewfinderpanoramas_org3.htm) for coverage).
 - Some disk space (tens of gigabytes) for tile cache. Tiles are relatively small, like 15 KiB for tile (png image).
 - 500 MiB of ram for one rendering thread

Right now, it is combination of apache http server, memcache for synchronization and php and python scripts. For production deployment I would imagine little bit different setup. Like Nginx with custom plugin, Kafka queues and Python workers... Depends what is your current backend stack. Sorry, but I have to refuse the offer for collaboration, despite that such project would be interesting. I'm saturated by my daily job.

Regards, Lukas

**Comment by janvonquaeldich** [comment]
Hi Lukas,
thank you very much for your very detailed reply, that's very much appreciated! How sad you can't do it though :)
I'll try to hire someone for this job.
All the best to you, and thank you very much again for this project!
Yours, Jan
